// GENERATED by scripts/build-simulado-100.js — do not hand-edit ids here.
// To swap a question after Karina's review, edit the OVERRIDES in that script
// and re-run with --apply, or replace an id in place (keep 20 per bloco).
//
// 100 REAL past-Revalida (INEP) questions, 5 blocos of 20 by grande área,
// editions 2020–2025.2 mixed, incidence-weighted topic coverage, deduped
// against /questoes-revalida (MAGNET_ALL_IDS) including cross-listed copies.

export type SimuladoBloco = {
  key: string;
  label: string;
  questionIds: number[];
};

export const SIMULADO_BLOCOS: SimuladoBloco[] = [
  {
    key: "clinica-medica",
    label: "Clínica Médica",
    questionIds: [
      3233, 3114, 2844, 2865, 3107, 2669, 3089, 2685, 2678, 2529,
      2822, 3092, 2915, 2892, 3096, 2695, 2699, 3342, 2541, 2705,
    ],
  },
  {
    key: "cirurgia",
    label: "Cirurgia",
    questionIds: [
      2582, 2609, 2564, 2619, 2589, 2598, 2638, 2629, 2557, 3250,
      2592, 2604, 2547, 2571, 2631, 2642, 2622, 2552, 2553, 2567,
    ],
  },
  {
    key: "go",
    label: "Ginecologia e Obstetrícia",
    questionIds: [
      2954, 2737, 2798, 2997, 2746, 2811, 2938, 2961, 2992, 2761,
      2769, 2978, 3014, 3009, 2930, 2727, 2781, 2786, 3255, 2973,
    ],
  },
  {
    key: "pediatria",
    label: "Pediatria",
    questionIds: [
      3045, 3277, 3031, 3263, 3061, 3039, 3305, 3081, 3023, 3302,
      3030, 3308, 3070, 3272, 3330, 3334, 3075, 3262, 3025, 3312,
    ],
  },
  {
    key: "saude-coletiva",
    label: "Saúde Coletiva",
    questionIds: [
      3174, 3291, 3164, 3215, 3226, 3211, 3207, 3349, 3199, 3223,
      3202, 3168, 3286, 3161, 3216, 3229, 3212, 3204, 3350, 3200,
    ],
  },
];

export const SIMULADO_100_IDS: number[] = SIMULADO_BLOCOS.flatMap((b) => b.questionIds);
export const SIMULADO_TOTAL = SIMULADO_100_IDS.length; // 100
