import "server-only";

import { createAdminClient } from "@/lib/supabase/admin";
import { CLINACT_PLANS, type ClinactPlanKey } from "./plans";
import {
  createCustomer,
  createPlan,
  createSubscription,
  customerCardToken,
  findSubscriptionByReference,
  getSubscriptionsEnv,
  isIdempotencyConflict,
  listInvoices,
  listPlans,
  reconcileByReference,
  PagBankSubscriptionsError,
  type PagBankAuditEntry,
  type PagBankSubscription,
} from "@/lib/pagbank/subscriptions";

/**
 * The ClinAct subscription flow: plan → subscriber (card encrypted in the
 * browser) → subscription → access.
 *
 * TWO RULES GOVERN EVERYTHING HERE, both learned in sandbox and both costing
 * real money if broken:
 *
 * 1. ACCESS FOLLOWS THE PAID INVOICE. POST /subscriptions answers 201 even when
 *    the card was declined — the subscription is simply born OVERDUE. And after
 *    a recovered charge the invoice reads PAID minutes before the subscription
 *    turns ACTIVE. So the invoice, not the status, decides.
 *
 * 2. A RETRY NEVER GETS A NEW IDEMPOTENCY KEY. PagBank does not deduplicate on
 *    reference_id: the same request twice creates a second subscription and
 *    charges it again. Every attempt carries one key, derived from the attempt
 *    id the browser generated; a replay answers 409 and we reconcile instead.
 *
 * The CVV passes through this module once, as an argument, on its way to
 * PagBank. It is never stored, never logged (the audit sink strips it by key),
 * and never attached to an error.
 */

/**
 * Refuses the one combination that would hand out real access for a test card:
 * the LIVE site talking to the PagBank SANDBOX. Vercel already holds the
 * sandbox token, so without this a logged-in visitor who found the URL could
 * "pay" with 5555666677778884 and be granted a subscription.
 *
 * Production hosting must be pointed at production PagBank, or the checkout
 * stays shut.
 */
export function subscriptionsUnavailable(): boolean {
  return process.env.VERCEL_ENV === "production" && getSubscriptionsEnv() !== "production";
}

export type SubscribeInput = {
  userId: string;
  email: string;
  /** Name as printed on the card. */
  name: string;
  /** CPF, digits only. */
  taxId: string;
  planKey: ClinactPlanKey;
  encryptedCard: string;
  securityCode: string;
  /**
   * One id per checkout attempt, generated by the browser and kept across
   * retries of THAT attempt. It becomes the reference_id and the idempotency
   * keys, which is what makes a resubmit safe.
   */
  attemptId: string;
  /** REQUIRED by PagBank: POST /customers refuses a subscriber without phones. */
  phone: { area: string; number: string };
};

export type SubscribeResult =
  | { ok: true; state: "paid"; subscriptionId: string; paidUntil: string }
  | { ok: true; state: "pending"; subscriptionId: string }
  | { ok: false; error: string };

/** pt-BR, and never leaks PagBank's wording to the student. */
const GENERIC_ERROR =
  "Não foi possível concluir a assinatura. Nenhuma cobrança foi feita. Tente novamente em alguns instantes.";
const DECLINED_ERROR =
  "O pagamento não foi aprovado pelo emissor do cartão. Confira os dados ou use outro cartão — nenhum valor foi cobrado.";
const DUPLICATE_CUSTOMER_ERROR =
  "Já existe um cadastro no PagBank com este CPF. Fale com o suporte para vincular a sua assinatura.";

/** Alphanumeric only, PagBank's rule for the idempotency key. */
function key(...parts: string[]): string {
  return parts.join("").replace(/[^a-zA-Z0-9]/g, "").slice(0, 200);
}

/**
 * Records every PagBank call. Deliberately tolerant: a failed audit write must
 * never cost a student their subscription, so the sink swallows its own errors
 * (the client also wraps it).
 */
function auditSink(userId: string, referenceId: string) {
  const env = getSubscriptionsEnv();
  return async (entry: PagBankAuditEntry) => {
    const admin = createAdminClient();
    await admin.from("pagbank_subscription_api_calls").insert({
      user_id: userId,
      reference_id: referenceId,
      environment: env,
      method: entry.method,
      path: entry.path,
      status: entry.status,
      request: entry.request as Record<string, unknown> | null,
      response: entry.response as Record<string, unknown> | null,
    });
  };
}

/**
 * The PagBank plan id for a ClinAct plan, created on first use.
 *
 * Plans are per-environment and per-credential, so production starts empty:
 * the first subscriber creates them.
 *
 * THE PRICE IS PART OF THE REFERENCE (`clinact-mensal-2990`), and the amount is
 * checked again after the lookup. Matching on `clinact-mensal` alone would mean
 * that changing the price in plans.ts keeps charging whatever the old PagBank
 * plan says — the exact drift Karina's decision 2 exists to prevent, and it
 * would be invisible: the page would show the new price and the card would be
 * charged the old one. A changed price can now only ever create a new plan.
 */
async function ensurePlanId(planKey: ClinactPlanKey, audit: ReturnType<typeof auditSink>): Promise<string> {
  const plan = CLINACT_PLANS[planKey];
  const referenceId = `clinact-${planKey}-${plan.amount_cents}`;

  const { plans } = await listPlans();
  const existing = plans?.find(
    (p) =>
      p.reference_id === referenceId &&
      p.status === "ACTIVE" &&
      p.amount?.value === plan.amount_cents &&
      p.interval?.unit === plan.interval,
  );
  if (existing) return existing.id;

  const created = await createPlan({
    reference_id: referenceId,
    name: `ClinAct ${plan.label}`,
    description: `Assinatura ${plan.label.toLowerCase()} do ClinAct`,
    amount_cents: plan.amount_cents,
    interval: { unit: plan.interval, length: plan.interval_count },
    audit,
  });
  return created.id;
}

/** PagBank returns `next_invoice_at` as YYYY-MM-DD; fall back to one period. */
function paidUntilFrom(subscription: PagBankSubscription, planKey: ClinactPlanKey): string {
  if (subscription.next_invoice_at) {
    const parsed = new Date(`${subscription.next_invoice_at}T12:00:00-03:00`);
    if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
  }
  const fallback = new Date();
  if (planKey === "anual") fallback.setFullYear(fallback.getFullYear() + 1);
  else fallback.setMonth(fallback.getMonth() + 1);
  return fallback.toISOString();
}

async function anyInvoicePaid(subscriptionId: string): Promise<boolean> {
  try {
    const { invoices } = await listInvoices(subscriptionId);
    return (invoices ?? []).some((i) => i.status === "PAID");
  } catch {
    return false;
  }
}

/**
 * Grants access. `paid_until` only ever moves FORWARD — the invariant from
 * schema-patch-clinact.sql — so a slow webhook arriving after a renewal can
 * never shorten what a student already paid for.
 */
async function grantAccess(userId: string, paidUntil: string): Promise<void> {
  const admin = createAdminClient();
  const { data: current } = await admin
    .from("user_product_access")
    .select("paid_until")
    .eq("user_id", userId)
    .eq("product", "clinact")
    .maybeSingle();

  const furthest =
    current?.paid_until && new Date(current.paid_until) > new Date(paidUntil)
      ? current.paid_until
      : paidUntil;

  await admin.from("user_product_access").upsert(
    {
      user_id: userId,
      product: "clinact",
      source: "subscription",
      paid_until: furthest,
      updated_at: new Date().toISOString(),
    },
    { onConflict: "user_id,product" },
  );
}

async function recordSubscription(input: {
  userId: string;
  referenceId: string;
  subscription: PagBankSubscription | null;
  customerId: string | null;
  planKey: ClinactPlanKey;
  planId: string | null;
  card?: { brand?: string; last?: string } | null;
}): Promise<void> {
  const admin = createAdminClient();
  await admin.from("clinact_subscriptions").upsert(
    {
      user_id: input.userId,
      reference_id: input.referenceId,
      pagbank_subscription_id: input.subscription?.id ?? null,
      pagbank_customer_id: input.customerId,
      plan_key: input.planKey,
      pagbank_plan_id: input.planId,
      status: input.subscription?.status ?? null,
      card_brand: input.card?.brand ?? null,
      card_last_digits: input.card?.last ?? null,
      environment: getSubscriptionsEnv(),
      updated_at: new Date().toISOString(),
    },
    { onConflict: "user_id" },
  );
}

export async function subscribeToClinact(input: SubscribeInput): Promise<SubscribeResult> {
  const referenceId = `clinact-${input.planKey}-${input.attemptId}`.slice(0, 64);
  const audit = auditSink(input.userId, referenceId);

  let planId: string;
  try {
    planId = await ensurePlanId(input.planKey, audit);
  } catch {
    return { ok: false, error: GENERIC_ERROR };
  }

  // ── The subscriber, with the card encrypted in their browser ──────────────
  let customerId: string;
  let cardToken: string | null;
  let card: { brand?: string; last?: string } | null = null;
  try {
    const customer = await createCustomer({
      reference_id: referenceId,
      name: input.name,
      email: input.email,
      tax_id: input.taxId,
      phone: input.phone,
      encrypted_card: input.encryptedCard,
      idempotency_key: key(input.attemptId, "cust"),
      audit,
    });
    customerId = customer.id;
    cardToken = customerCardToken(customer);
    const registered = customer.billing_info?.[0]?.card;
    card = registered ? { brand: registered.brand, last: registered.last_digits } : null;
  } catch (err) {
    if (err instanceof PagBankSubscriptionsError && err.status === 409) {
      return { ok: false, error: DUPLICATE_CUSTOMER_ERROR };
    }
    return { ok: false, error: GENERIC_ERROR };
  }

  if (!cardToken) return { ok: false, error: GENERIC_ERROR };

  // ── The subscription. This is the call that charges. ──────────────────────
  let subscription: PagBankSubscription | null = null;
  try {
    subscription = await createSubscription({
      reference_id: referenceId,
      plan_id: planId,
      customer_id: customerId,
      card_token: cardToken,
      security_code: input.securityCode,
      idempotency_key: key(input.attemptId, "sub"),
      audit,
    });
  } catch (err) {
    // A replayed key means the first attempt may already have gone through.
    // Look it up — never charge again to find out.
    if (isIdempotencyConflict(err)) {
      const outcome = await reconcileByReference(referenceId);
      if (outcome.kind === "paid") {
        const found = await findSubscriptionByReference(referenceId);
        if (found) {
          await recordSubscription({ userId: input.userId, referenceId, subscription: found, customerId, planKey: input.planKey, planId, card });
          await grantAccess(input.userId, paidUntilFrom(found, input.planKey));
          return { ok: true, state: "paid", subscriptionId: outcome.subscriptionId, paidUntil: paidUntilFrom(found, input.planKey) };
        }
      }
      if (outcome.kind === "pending") {
        return { ok: true, state: "pending", subscriptionId: outcome.subscriptionId };
      }
    }
    await recordSubscription({ userId: input.userId, referenceId, subscription: null, customerId, planKey: input.planKey, planId, card });
    return { ok: false, error: GENERIC_ERROR };
  }

  await recordSubscription({ userId: input.userId, referenceId, subscription, customerId, planKey: input.planKey, planId, card });

  // 201 does NOT mean paid. Ask the invoice.
  const paid = await anyInvoicePaid(subscription.id);
  if (!paid) {
    // OVERDUE at creation means the issuer declined the first charge.
    if (subscription.status === "OVERDUE" || subscription.status === "PENDING_ACTION") {
      return { ok: false, error: DECLINED_ERROR };
    }
    return { ok: true, state: "pending", subscriptionId: subscription.id };
  }

  const paidUntil = paidUntilFrom(subscription, input.planKey);
  await grantAccess(input.userId, paidUntil);
  return { ok: true, state: "paid", subscriptionId: subscription.id, paidUntil };
}

