/**
 * ClinAct — shared types for the case engine.
 *
 * The `CaseDoc` shape is THE document: the editor edits it, the importer
 * produces it, `clinact_save_case` persists it, `clinact_case_document`
 * returns it, and `clinact_case_versions.snapshot` freezes it. One shape,
 * every direction, so nothing can drift between the panel and the DB.
 *
 * Pure types + constants only — safe to import from client components.
 */

export const FORMATS = ["codigo_clinico", "clinica_em_cena", "decisao_30s", "ponto_de_virada"] as const;
export type CaseFormat = (typeof FORMATS)[number];

export const SKILLS = ["conectar", "conduzir", "priorizar", "reavaliar"] as const;
export type Skill = (typeof SKILLS)[number];

export const DIFFICULTIES = ["basica", "intermediaria", "avancada"] as const;
export type Difficulty = (typeof DIFFICULTIES)[number];

export const STATUSES = ["draft", "published", "archived"] as const;
export type CaseStatus = (typeof STATUSES)[number];

export const CONFIDENCES = ["baixa", "media", "alta"] as const;
export type Confidence = (typeof CONFIDENCES)[number];

export const QUALITIES = ["ideal", "aceitavel", "inadequada", "prejudicial"] as const;
export type Quality = (typeof QUALITIES)[number];

/** Frozen 2026-08-28 (§2.2). Changing these rewrites every historical percentage. */
export const QUALITY_WEIGHTS: Record<Quality, number> = {
  ideal: 1.0,
  aceitavel: 0.6,
  inadequada: 0.2,
  prejudicial: 0.0,
};

export const STEP_KINDS = [
  "narrativa",
  "pistas",
  "pergunta",
  "ordenar",
  "cena_conduta",
  "investigacao",
  "novo_dado",
  "reavaliacao",
  "confianca",
  "feedback",
  "seducao",
  "custo_do_atraso",
  "midia",
  "cronometro",
  "leve_deste_caso",
  "prontuario",
  "codigo_decifrado",
] as const;
export type StepKind = (typeof STEP_KINDS)[number];

/** Generated by the system, never authored. */
export const GENERATED_KINDS: readonly StepKind[] = ["prontuario", "codigo_decifrado"];

/** Steps the student answers. Everything else is shown or attached. */
export const DECISION_KINDS: readonly StepKind[] = ["pergunta", "reavaliacao", "ordenar", "cena_conduta", "investigacao"];

/**
 * Decisions whose answer is a SET of options rather than one (Karina,
 * 2026-09-03). Only Clínica em Cena uses it: investigation is part of the
 * promise of CONDUZIR, and she asked not to extend it to the other formats
 * merely because it would work there.
 */
export const MULTI_SELECT_KINDS: readonly StepKind[] = ["investigacao"];

/** Format → the skill it trains (the case's `primary_skill`). */
export const FORMAT_SKILL: Record<CaseFormat, Skill> = {
  codigo_clinico: "conectar",
  clinica_em_cena: "conduzir",
  decisao_30s: "priorizar",
  ponto_de_virada: "reavaliar",
};

/**
 * The verb each format trains, as the student meets it in the library
 * (Karina, 2026-09-02: "Código Clínico — CONECTAR"). Both doors into the
 * library lead with it, because the format IS the skill.
 */
export const SKILL_LABELS: Record<Skill, string> = {
  conectar: "CONECTAR",
  conduzir: "CONDUZIR",
  priorizar: "PRIORIZAR",
  reavaliar: "REAVALIAR",
};

/**
 * The colour token each format wears in the library, mirroring how Revalida
 * gives every content type its own colour (Karina, 2026-09-02). Tokens only —
 * the values live in globals.css, light and dark.
 */
export const FORMAT_COLOR_VARS: Record<CaseFormat, string> = {
  codigo_clinico: "var(--c-codigo-clinico)",
  clinica_em_cena: "var(--c-clinica-em-cena)",
  decisao_30s: "var(--c-decisao-30s)",
  ponto_de_virada: "var(--c-ponto-de-virada)",
};

/** One line per format — what the student is about to practise. */
export const FORMAT_BLURBS: Record<CaseFormat, string> = {
  codigo_clinico: "Juntar pistas soltas até o caso fechar.",
  clinica_em_cena: "Conduzir um plantão, cena a cena, com o relógio correndo.",
  decisao_30s: "Decidir rápido, quando a ordem das condutas é o que importa.",
  ponto_de_virada: "Rever a hipótese quando um dado novo muda tudo.",
};

export const FORMAT_LABELS: Record<CaseFormat, string> = {
  codigo_clinico: "Código Clínico",
  clinica_em_cena: "Clínica em Cena",
  decisao_30s: "Decisão em 30 Segundos",
  ponto_de_virada: "Ponto de Virada",
};

/** §2.1 — one JSONB shape, used in steps, clues and revealed findings. */
export type Media = {
  type: "image" | "audio" | "video" | string;
  /** Public URL (Bunny). Empty string = placeholder, not yet uploaded. */
  url: string;
  /** Filename as authored (`[imagem: ecg-caso-12.jpg]`). Identity for re-import + round trip. */
  file?: string;
  caption?: string;
  alt?: string;
  transcript?: string;
};

export type RevealCategory = "sabemos" | "encontramos" | "fizemos" | "estado";
export const REVEAL_CATEGORIES: readonly RevealCategory[] = ["sabemos", "encontramos", "fizemos", "estado"];

export type Reveal = { cat: RevealCategory; texto: string; midia?: Media };

/** `clinact_options.effect` */
export type Effect = {
  revela?: Reveal[];
  estado?: Record<string, string>;
  relogio?: number;
};

export type OptionDoc = {
  id?: number;
  position: number;
  label: string;
  is_correct: boolean;
  quality?: Quality | null;
  feedback?: string | null;
  seduction?: string | null;
  effect: Effect;
  next_scene_key?: string | null;
};

// ── Per-kind `content` shapes ─────────────────────────────────────────────────
// Each kind's content is validated by the Zod schema in ./schemas.ts and the
// admin form is generated from the same field list, so a new kind is one entry
// there and zero DB work.

export type ContentNarrativa = { text: string; media?: Media[] };
export type ContentPistas = Record<string, never>; // clues live in `clues`
export type ContentPergunta = { prompt: string; media?: Media[] };
export type ContentOrdenar = { prompt: string; items: string[]; media?: Media[] };
export type ContentCena = { text: string; media?: Media[] };
/**
 * The investigation block: one prompt, and the options are the exams/actions
 * on offer. Each option carries its own quality and its own result (in
 * `effect.revela`, text plus image or audio), so ordering it is what makes that
 * information exist.
 */
export type ContentInvestigacao = { prompt: string; media?: Media[] };
export type ContentNovoDado = { text: string; media?: Media[] };
export type ContentReavaliacao = { prompt: string; media?: Media[] };
export type ContentConfianca = Record<string, never>;
export type ContentFeedback = { text: string; media?: Media[] };
export type ContentSeducao = { text: string };
export type ContentCustoDoAtraso = { text: string; window?: string; media?: Media[] };
export type ContentMidia = { media: Media[] };
export type ContentCronometro = { seconds: number };
export type ContentLeveDesteCaso = { text: string };

export type StepContent =
  | ContentNarrativa
  | ContentPergunta
  | ContentOrdenar
  | ContentCena
  | ContentInvestigacao
  | ContentNovoDado
  | ContentReavaliacao
  | ContentConfianca
  | ContentFeedback
  | ContentSeducao
  | ContentCustoDoAtraso
  | ContentMidia
  | ContentCronometro
  | ContentLeveDesteCaso
  | Record<string, unknown>;

export type StepDoc = {
  id?: number;
  position: number;
  kind: StepKind;
  enabled: boolean;
  scene_key?: string | null;
  skill?: Skill | null;
  content: StepContent & Record<string, unknown>;
  options: OptionDoc[];
};

export type ClueDoc = {
  id?: number;
  position: number;
  label: string;
  detail?: string | null;
  media?: Media | null;
  category?: string | null;
  is_red_herring: boolean;
  red_herring_reason?: string | null;
  cluster?: string | null;
};

export type CaseDoc = {
  id?: number;
  slug: string;
  format: CaseFormat;
  title: string;
  specialty_id?: number | null;
  topic_id?: number | null;
  specialty_text?: string | null;
  topic_text?: string | null;
  difficulty: Difficulty;
  primary_skill: Skill;
  est_minutes?: number | null;
  summary?: string | null;
  takeaway?: string | null;
  final_key?: string | null;
  notes?: string | null;
  status?: CaseStatus;
  revision?: number;
  published_at?: string | null;
  /** Editorial flag (Karina 2026-08-31): one free sample case per format. */
  is_free?: boolean;
  steps: StepDoc[];
  clues: ClueDoc[];
};

/** Row shape of `clinact_cases` for lists. */
export type CaseListRow = {
  id: number;
  slug: string;
  format: CaseFormat;
  title: string;
  specialty_id: number | null;
  topic_id: number | null;
  specialty_text: string | null;
  topic_text: string | null;
  difficulty: Difficulty;
  est_minutes: number | null;
  summary: string | null;
  status: CaseStatus;
  revision: number;
  published_at: string | null;
  is_free: boolean;
  updated_at: string;
};

/** Runtime state folded into `clinact_attempts.state` (§2.4). */
export type AttemptState = {
  /** Index into the enabled step list of the next step to show. */
  cursor: number;
  /** step_id → what was answered. */
  answered: Record<string, AnsweredStep>;
  /** Prontuário Vivo drawers, folded from chosen effects. */
  revealed: Reveal[];
  estado: Record<string, string>;
  relogio: number;
  scene_key?: string | null;
};

export type AnsweredStep = {
  option_id?: number | null;
  order?: number[];
  /** Investigation: every option the student ordered, by id. */
  selected?: number[];
  is_correct: boolean;
  weight: number;
  confidence?: Confidence | null;
  time_ms?: number | null;
};

export const CLINACT_CDN_BASE = "https://medhelpspace.b-cdn.net";
export const CLINACT_MEDIA_PREFIX = "clinact/media";
