// The public social profiles, in the order they appear everywhere they appear.
//
// ONE list, two renderings: the marketing footer (landing-footer.tsx) draws
// inline SVG, the e-mail footer (email-render.ts) points at a hosted PNG because
// Gmail and Outlook strip inline <svg> and reject data: URIs. Before this module
// the Instagram handle was hardcoded in both files with a comment asking whoever
// changed one to remember the other — which is exactly the kind of thing nobody
// remembers. Add a network here and both surfaces pick it up.
//
// PNGs are generated by scripts/build-social-email-icons.js so the glyphs stay a
// matched set; re-run it after adding an entry.

export type SocialProfile = {
  /** Stable id — the marketing footer keys its SVG component off this. */
  key: "instagram" | "youtube" | "tiktok";
  /** Accessible name / img alt. */
  label: string;
  url: string;
  handle: string;
  /** Filename under /public/brand, served absolute in e-mail. */
  emailIcon: string;
};

export const SOCIAL_PROFILES: SocialProfile[] = [
  {
    key: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/medhelpspace/",
    handle: "@medhelpspace",
    emailIcon: "instagram-icon-email.png",
  },
  {
    key: "youtube",
    label: "YouTube",
    url: "https://www.youtube.com/@medhelpspace",
    handle: "@medhelpspace",
    emailIcon: "youtube-icon-email.png",
  },
  {
    key: "tiktok",
    label: "TikTok",
    // NOTE: the TikTok handle is NOT the same as the other two — it carries the
    // `_revalida` suffix. Anything that prints "one handle for all our socials"
    // would be wrong, which is why the e-mail footer shows icons plus a tagline
    // rather than a single handle.
    url: "https://www.tiktok.com/@medhelpspace_revalida",
    handle: "@medhelpspace_revalida",
    emailIcon: "tiktok-icon-email.png",
  },
];

// Karina, 2026-07-26: a bare handle gave the reader no reason to tap it; this says
// what is on the other side. Kept when the row went from one network to three, and
// extended to NAME the networks.
//
// The naming is not decoration. The row above is icons only, and a large share of
// Gmail recipients read with images off — where those icons collapse to broken
// squares whose alt text is clipped by the 20px box ("You", "Tik"). This line is
// then the only thing left that says we are on these platforms at all.
export const SOCIAL_TAGLINE = "Dicas de Revalida no Instagram, YouTube e TikTok";
