-- Rollback for the 134-page *-simulados batch conversion run on 2026-05-22.
-- Reverts every page back to type='text-lesson' and deletes the inserted
-- quiz_questions rows. Source lessons rows were preserved during apply
-- (PoC convention), so reverting type is sufficient.
--
-- NOTE: bradiarritmias-simulados is intentionally OMITTED — it's the PoC
-- and was already converted before this batch. abscesso-pulmonar-simulados
-- is also omitted — it was a pre-existing H5P quiz, not in this batch.

BEGIN;

DELETE FROM quiz_questions
WHERE page_id IN (
  SELECT id FROM pages WHERE slug IN (
    -- cardiologia (6)
    'cardiopatia-congenita-simulados',
    'hipertensao-arterial-simulados',
    'sindrome-coronariana-aguda-simulados',
    'tamponamento-cardiaco-simulados',
    'taquiarritmias-simulados',
    'valvopatias-simulados',
    -- cirurgia-geral (25)
    'abdome-agudo-hemorragico-simulados',
    'abdome-agudo-obstrutivo-simulados',
    'abdome-agudo-perfurativo-simulados',
    'abdome-agudo-vascular-simulados',
    'apendicite-simulados',
    'cancer-de-colorretal-simulados',
    'cancer-de-esofago-simulados',
    'cancer-de-estomago-simulados',
    'cirurgia-pediatrica-simulados',
    'colecistite-simulados',
    'diverticulite-simulados',
    'doencas-orificiais-simulados',
    'estenose-hipertrofica-do-piloro-simulados',
    'hemorragia-digestiva-simulados',
    'hernias-simulados',
    'invaginacao-intestinal-em-lactente-simulados',
    'pancreatite-simulados',
    'perioperatorio-simulados',
    'queimados-simulados',
    'trauma-atendimento-inicial-e-vias-areas-simulados',
    'trauma-de-torax-simulados',
    'trauma-osteomielite-simulados',
    'trauma-raquimedular-simulados',
    'tumor-de-pancreas-simulados',
    'tumor-neuroendocrino-infantil-simulados',
    -- dermatologia (6)
    'doencas-eczematosas-simulados',
    'doencas-eritematodescamativas-simulados',
    'farmacodermias-simulados',
    'micoses-simulados',
    'neoplasias-em-dermatologia-simulados',
    'parasitoses-cutaneas-simulados',
    -- emergencia (2)
    'acls-simulados',
    'choque-simulados',
    -- endocrinologia (6)
    'diabetes-simulados',
    'doencas-das-adrenais-simulados',
    'doencas-das-paratireoides-simulados',
    'hipotireoidismo-simulados',
    'osteoporose-simulados',
    'tireotoxicose-simulados',
    -- gastroenterologia (6)
    'cirrose-simulados',
    'doenca-do-refluxo-gastroesofagico-simulados',
    'doencas-inflamatorias-intestinais-simulados',
    'hepatites-virais-simulados',
    'sindrome-do-intestino-irritavel-simulados',
    'ulcera-peptica-e-h-pylori-simulados',
    -- ginecologia (18)
    'amenorreia-simulados',
    'anticoncepcao-simulados',
    'cancer-de-endometrio-simulados',
    'cancer-de-mama-simulados',
    'cancer-de-ovario-simulados',
    'cervicite-e-vulvovaginite-simulados',
    'climaterio-simulados',
    'disturbio-do-desenvolvimento-sexual-simulados',
    'doenca-inflamatoria-pelvica-simulados',
    'doencas-benignas-da-mama-simulados',
    'doencas-benignas-do-utero-simulados',
    'doencas-ovarianas-simulados',
    'endometriose-simulados',
    'hpv-e-cancer-de-colo-simulados',
    'patologias-da-vulva-simulados',
    'planejamento-familiar-simulados',
    'sangramento-uterino-anormal-simulados',
    'sindrome-dos-ovarios-policisticos-simulados',
    -- hematologia (6)
    'anemia-ferropriva-simulados',
    'anemia-megaloblastica-simulados',
    'disturbio-da-hemostasia-primaria-simulados',
    'disturbio-da-hemostasia-secundaria-simulados',
    'linfomas-simulados',
    'mieloma-multiplo-simulados',
    -- infectologia (8)
    'arboviroses-simulados',
    'hanseniase-simulados',
    'hiv-simulados',
    'leptospirose-simulados',
    'mononucleose-simulados',
    'parasitoses-intestinais-simulados',
    'tetano-simulados',
    'ulceras-genitais-ist-simulados',
    -- nefrologia (2)
    'injuria-renal-aguda-simulados',
    'sindrome-nefrotica-simulados',
    -- neurologia (8)
    'avc-hemorragico-simulados',
    'avc-isquemico-simulados',
    'cefaleias-simulados',
    'doenca-de-parkinson-simulados',
    'hipertensao-intracraniana-simulados',
    'infeccoes-neurologicas-simulados',
    'patologias-da-coluna-vertebral-simulados',
    'sindrome-de-guillain-barre-simulados',
    -- obstetricia (13)
    'aborto-simulados',
    'assistencia-clinica-ao-parto-simulados',
    'gestacao-ectopica-simulados',
    'infeccao-urinaria-na-gestacao-simulados',
    'isoimunizacao-rh-simulados',
    'puerperio-simulados',
    'relacoes-uterofetais-simulados',
    'rotura-prematura-de-membranas-simulados',
    'sifilis-na-gestacao-simulados',
    'sindromes-hemorragicas-da-gestacao-simulados',
    'sindromes-hipertensivas-na-gestacao-simulados',
    'toxoplasmose-na-gestacao-simulados',
    'vitalidade-fetal-simulados',
    -- pediatria (14)
    'aleitamento-materno-simulados',
    'alimentacao-complementar-do-lactente-simulados',
    'bronquiolite-simulados',
    'convulsao-febril-simulados',
    'desnutricao-e-obesidade-na-infancia-simulados',
    'diarreia-e-desidratacao-simulados',
    'disturbios-do-crescimento-e-desenvolvimento-simulados',
    'faringoamigdalite-estreptococica-simulados',
    'ictericia-neonatal-simulados',
    'laringite-viral-crupe-simulados',
    'malformacoes-congenitas-simulados',
    'maus-tratos-e-prevencoes-de-acidentes-na-infancia-simulados',
    'puericultura-simulados',
    'sepse-neonatal-simulados',
    -- pneumologia (6)
    'asma-simulados',
    'derrame-pleural-simulados',
    'dpoc-simulados',
    'nodulo-e-cancer-de-pulmao-simulados',
    'pneumonoa-simulados',
    'tuberculose-simulados',
    -- saude-coletiva (8)
    'atencao-ao-idoso-simulados',
    'atencao-basica-simulados',
    'bioestatistica-simulados',
    'declaracao-de-obito-simulados',
    'etica-medica-simulados',
    'processo-saude-doenca-simulados',
    'sus-historico-principios-e-diretrizes-simulados',
    'vigilancia-epidemiologica-simulados'
  )
);

UPDATE pages
SET type = 'text-lesson'
WHERE slug IN (
  'cardiopatia-congenita-simulados','hipertensao-arterial-simulados','sindrome-coronariana-aguda-simulados',
  'tamponamento-cardiaco-simulados','taquiarritmias-simulados','valvopatias-simulados',
  'abdome-agudo-hemorragico-simulados','abdome-agudo-obstrutivo-simulados','abdome-agudo-perfurativo-simulados',
  'abdome-agudo-vascular-simulados','apendicite-simulados','cancer-de-colorretal-simulados',
  'cancer-de-esofago-simulados','cancer-de-estomago-simulados','cirurgia-pediatrica-simulados',
  'colecistite-simulados','diverticulite-simulados','doencas-orificiais-simulados',
  'estenose-hipertrofica-do-piloro-simulados','hemorragia-digestiva-simulados','hernias-simulados',
  'invaginacao-intestinal-em-lactente-simulados','pancreatite-simulados','perioperatorio-simulados',
  'queimados-simulados','trauma-atendimento-inicial-e-vias-areas-simulados','trauma-de-torax-simulados',
  'trauma-osteomielite-simulados','trauma-raquimedular-simulados','tumor-de-pancreas-simulados',
  'tumor-neuroendocrino-infantil-simulados','doencas-eczematosas-simulados','doencas-eritematodescamativas-simulados',
  'farmacodermias-simulados','micoses-simulados','neoplasias-em-dermatologia-simulados',
  'parasitoses-cutaneas-simulados','acls-simulados','choque-simulados','diabetes-simulados',
  'doencas-das-adrenais-simulados','doencas-das-paratireoides-simulados','hipotireoidismo-simulados',
  'osteoporose-simulados','tireotoxicose-simulados','cirrose-simulados',
  'doenca-do-refluxo-gastroesofagico-simulados','doencas-inflamatorias-intestinais-simulados',
  'hepatites-virais-simulados','sindrome-do-intestino-irritavel-simulados','ulcera-peptica-e-h-pylori-simulados',
  'amenorreia-simulados','anticoncepcao-simulados','cancer-de-endometrio-simulados','cancer-de-mama-simulados',
  'cancer-de-ovario-simulados','cervicite-e-vulvovaginite-simulados','climaterio-simulados',
  'disturbio-do-desenvolvimento-sexual-simulados','doenca-inflamatoria-pelvica-simulados',
  'doencas-benignas-da-mama-simulados','doencas-benignas-do-utero-simulados','doencas-ovarianas-simulados',
  'endometriose-simulados','hpv-e-cancer-de-colo-simulados','patologias-da-vulva-simulados',
  'planejamento-familiar-simulados','sangramento-uterino-anormal-simulados',
  'sindrome-dos-ovarios-policisticos-simulados','anemia-ferropriva-simulados','anemia-megaloblastica-simulados',
  'disturbio-da-hemostasia-primaria-simulados','disturbio-da-hemostasia-secundaria-simulados',
  'linfomas-simulados','mieloma-multiplo-simulados','arboviroses-simulados','hanseniase-simulados',
  'hiv-simulados','leptospirose-simulados','mononucleose-simulados','parasitoses-intestinais-simulados',
  'tetano-simulados','ulceras-genitais-ist-simulados','injuria-renal-aguda-simulados',
  'sindrome-nefrotica-simulados','avc-hemorragico-simulados','avc-isquemico-simulados','cefaleias-simulados',
  'doenca-de-parkinson-simulados','hipertensao-intracraniana-simulados','infeccoes-neurologicas-simulados',
  'patologias-da-coluna-vertebral-simulados','sindrome-de-guillain-barre-simulados','aborto-simulados',
  'assistencia-clinica-ao-parto-simulados','gestacao-ectopica-simulados','infeccao-urinaria-na-gestacao-simulados',
  'isoimunizacao-rh-simulados','puerperio-simulados','relacoes-uterofetais-simulados',
  'rotura-prematura-de-membranas-simulados','sifilis-na-gestacao-simulados',
  'sindromes-hemorragicas-da-gestacao-simulados','sindromes-hipertensivas-na-gestacao-simulados',
  'toxoplasmose-na-gestacao-simulados','vitalidade-fetal-simulados','aleitamento-materno-simulados',
  'alimentacao-complementar-do-lactente-simulados','bronquiolite-simulados','convulsao-febril-simulados',
  'desnutricao-e-obesidade-na-infancia-simulados','diarreia-e-desidratacao-simulados',
  'disturbios-do-crescimento-e-desenvolvimento-simulados','faringoamigdalite-estreptococica-simulados',
  'ictericia-neonatal-simulados','laringite-viral-crupe-simulados','malformacoes-congenitas-simulados',
  'maus-tratos-e-prevencoes-de-acidentes-na-infancia-simulados','puericultura-simulados',
  'sepse-neonatal-simulados','asma-simulados','derrame-pleural-simulados','dpoc-simulados',
  'nodulo-e-cancer-de-pulmao-simulados','pneumonoa-simulados','tuberculose-simulados',
  'atencao-ao-idoso-simulados','atencao-basica-simulados','bioestatistica-simulados',
  'declaracao-de-obito-simulados','etica-medica-simulados','processo-saude-doenca-simulados',
  'sus-historico-principios-e-diretrizes-simulados','vigilancia-epidemiologica-simulados'
);

COMMIT;
