#!/usr/bin/env python3
"""
parse-simulado-100-pdfs.py — turns Karina's two simulado PDFs into merged.json.

The free 100-question simulado (/simulado-revalida) is authored as two PDFs:

  simulado-100-questoes.pdf              enunciados + four alternatives, no key
  gabarito-comentado-simulado-100-questoes.pdf
                                         synthetic answer grid + per-question
                                         comentário / distratores / conceito-chave

This script parses both and writes `merged.json` — the importer's main input.
It does NOT write classification.json (Karina's área/tema list, keyed by question
number, regenerated by build-classification.py) or figure-urls.json (written by
upload-simulado-figures.js). Both survive a re-parse unchanged as long as the
question numbering does; this script asserts the figure-bearing questions still
match the ones figure-urls.json knows about.

The answer key is cross-validated three independent ways before anything is
written — the grid, the per-question "Alternativa correta: X", and the text of
that alternative matched back against the questions PDF. Any disagreement is a
hard failure: a wrong key on a funnel that grades 100 questions is worse than no
import at all.

Usage:
  python scripts/parse-simulado-100-pdfs.py --src <pdf folder> [--out data/simulado-100-v2]
  python scripts/parse-simulado-100-pdfs.py --src <pdf folder> --out <dir> --write

Dry run by default: parses, validates, prints a diff against the merged.json
already in --out, and writes nothing.

Requires PyMuPDF (`pip install pymupdf`).
"""

import argparse
import difflib
import json
import os
import re
import sys
import unicodedata

try:
    import fitz  # PyMuPDF
except ImportError:  # pragma: no cover
    sys.exit("PyMuPDF is required:  pip install pymupdf")

QUESTIONS_PDF = "simulado-100-questoes.pdf"
GABARITO_PDF = "gabarito-comentado-simulado-100-questoes.pdf"
EXPECTED = 100
LETTERS = "ABCD"

# Running headers/footers repeated on every page of both PDFs.
CHROME_LINES = {
    "MedHelpSpace | Revalida INEP",
    "MedHelpSpace",
    "Caderno definitivo",
    "Gabarito comentado definitivo",
}
CHROME_PATTERNS = [
    re.compile(r"^Vers[ãa]o definitiva\b.*$", re.I),
    re.compile(r"^\d{1,3}$"),  # bare page number
]

# The August 2026 caderno flattened every sub/superscript ("SpO2", "78.000/mm3",
# "166 x 100 mmHg"). Restore the typography the set has always been served with —
# an explicit whitelist, never a blanket digit rule (T4, B12, HbA1c must not move).
TYPOGRAPHY = [
    (re.compile(r"\bSpO2\b"), "SpO₂"),
    (re.compile(r"\bSatO2\b"), "SatO₂"),
    (re.compile(r"\bFiO2\b"), "FiO₂"),
    (re.compile(r"\bPaO2\b"), "PaO₂"),
    (re.compile(r"\bPaCO2\b"), "PaCO₂"),
    (re.compile(r"\bpCO2\b"), "pCO₂"),
    (re.compile(r"\bpO2\b"), "pO₂"),
    (re.compile(r"\bCO2\b"), "CO₂"),
    (re.compile(r"\bO2\b"), "O₂"),
    (re.compile(r"\bmm3\b"), "mm³"),
    (re.compile(r"\bcm3\b"), "cm³"),
    (re.compile(r"\bmm2\b"), "mm²"),
    (re.compile(r"\bcm2\b"), "cm²"),
    (re.compile(r"\bm2\b"), "m²"),
    # blood pressure "166 x 100 mmHg" → "166 × 100 mmHg"
    (re.compile(r"(?<=\d)\s*x\s*(?=\d{2,3}\s*mmHg)"), " × "),
    # legal-document numbering: "Nota Técnica no 222/2025" → "nº 222/2025". Scoped to
    # the naming words on purpose — a bare "no 3" is the preposition ("no 3º dia").
    (re.compile(r"\b(Nota T[ée]cnica|Portaria|Lei|Resolu[çc][ãa]o|RDC|Decreto|Instru[çc][ãa]o Normativa)\s+no\s+(?=\d)"),
     r"\1 nº "),
]


def fix_typography(s: str) -> str:
    for pattern, repl in TYPOGRAPHY:
        s = pattern.sub(repl, s)
    return s


def clean_lines(page):
    """Page text as stripped lines, with running chrome removed."""
    out = []
    for raw in page.get_text().split("\n"):
        t = raw.strip()
        if not t or t in CHROME_LINES:
            continue
        if any(p.match(t) for p in CHROME_PATTERNS):
            continue
        out.append(t)
    return out


def join(lines):
    return re.sub(r"\s+", " ", " ".join(lines)).strip()


RE_HEADER = re.compile(r"Quest[ãa]o\s+(\d{1,3})$")


def split_by_question(doc, skip_pages=()):
    """Group every line under the 'Questão N' header that precedes it."""
    blocks, cur = [], None
    for i, page in enumerate(doc):
        if i in skip_pages:
            continue
        for t in clean_lines(page):
            m = RE_HEADER.fullmatch(t)
            if m:
                if cur:
                    blocks.append(cur)
                cur = {"number": int(m.group(1)), "lines": [], "pages": {i}}
                continue
            if cur is not None:
                cur["lines"].append(t)
                cur["pages"].add(i)
    if cur:
        blocks.append(cur)
    return blocks


# ── questions PDF ─────────────────────────────────────────────────────────────

RE_ALT_SPLIT = re.compile(r"\(([A-D])\)\s*")


def parse_questions(path, errors):
    doc = fitz.open(path)
    figures = figure_questions(doc)
    parsed = {}
    for b in split_by_question(doc):
        n = b["number"]
        body = fix_typography(join(b["lines"]))
        parts = RE_ALT_SPLIT.split(body)
        stem = parts[0].strip()
        alts = {}
        for i in range(1, len(parts) - 1, 2):
            letter, text = parts[i], parts[i + 1].strip()
            if letter in alts:
                errors.append(f"Q{n}: alternative ({letter}) appears twice")
            alts[letter] = text
        if sorted(alts) != list(LETTERS):
            errors.append(f"Q{n}: expected alternatives A-D, found {sorted(alts) or 'none'}")
        parsed[n] = {
            "number": n,
            "enunciado": stem,
            "alternatives": [alts.get(l, "") for l in LETTERS],
            "has_figure": n in figures,
        }
    return parsed, figures


def figure_questions(doc):
    """Question numbers carrying an embedded figure.

    A figure page usually holds two questions, so the page is not enough: the
    owner is the last 'Questão N' header that starts above the image.
    """
    owners = set()
    for page in doc:
        images = page.get_images(full=True)
        if not images:
            continue
        heads = []
        for block in page.get_text("dict")["blocks"]:
            for line in block.get("lines", []):
                t = "".join(s["text"] for s in line["spans"]).strip()
                m = RE_HEADER.fullmatch(t)
                if m:
                    heads.append((line["spans"][0]["origin"][1], int(m.group(1))))
        heads.sort()
        for xref, *_ in images:
            rects = page.get_image_rects(xref)
            y = rects[0].y0 if rects else 0.0
            owner = None
            for hy, num in heads:
                if hy <= y:
                    owner = num
            if owner is not None:
                owners.add(owner)
    return owners


# ── gabarito PDF ──────────────────────────────────────────────────────────────

RE_SECTIONS = re.compile(
    r"Alternativa correta:\s*([A-D])\s*[-–—]\s*(.*?)\s*"
    r"Coment[áa]rio:\s*(.*?)\s*"
    r"Por que as outras est[ãa]o erradas\?\s*(.*?)\s*"
    r"Conceito[- ]chave:\s*(.*)$"
)


def parse_gabarito(path, errors):
    doc = fitz.open(path)
    grid = parse_grid(doc)
    parsed = {}
    # Pages 1-2 are the cover and the synthetic grid; per-question text starts after.
    for b in split_by_question(doc, skip_pages=(0, 1)):
        n = b["number"]
        body = join(b["lines"]).replace("✓", "").replace("●", "")
        body = fix_typography(re.sub(r"\s+", " ", body).strip())
        m = RE_SECTIONS.search(body)
        if not m:
            errors.append(f"Q{n}: gabarito section headings not found (comentário/distratores/conceito)")
            continue
        parsed[n] = {
            "number": n,
            "correct_letter": m.group(1),
            "correct_text": m.group(2).strip(),
            "comentario": m.group(3).strip(),
            "distratores": m.group(4).strip(),
            "conceito_chave": m.group(5).strip(),
        }
    return parsed, grid


def parse_grid(doc):
    """The GABARITO SINTÉTICO table: a question number followed by its letter."""
    toks = [t.strip() for t in doc[1].get_text().split("\n") if t.strip()]
    grid = {}
    for i, t in enumerate(toks):
        if re.fullmatch(r"\d{1,3}", t) and i + 1 < len(toks) and re.fullmatch(r"[A-D]", toks[i + 1]):
            n = int(t)
            if 1 <= n <= EXPECTED:
                grid[n] = toks[i + 1]
    return grid


# ── validation ────────────────────────────────────────────────────────────────

def norm(s):
    s = unicodedata.normalize("NFC", s or "")
    return re.sub(r"\s+", " ", s).strip().lower()


def cross_validate(questions, gabarito, grid, errors):
    """Three independent reads of the answer key must agree on all 100."""
    for n in range(1, EXPECTED + 1):
        q, g = questions.get(n), gabarito.get(n)
        if not q:
            errors.append(f"Q{n}: missing from the questions PDF")
        if not g:
            errors.append(f"Q{n}: missing from the gabarito PDF")
        if not (q and g):
            continue

        letter = g["correct_letter"]
        if grid.get(n) != letter:
            errors.append(f"Q{n}: grid says {grid.get(n)}, gabarito text says {letter}")

        alt = norm(q["alternatives"][LETTERS.index(letter)])
        stated = norm(g["correct_text"])
        # The gabarito restates the alternative; wrapping and trailing punctuation
        # vary, so compare on a generous prefix rather than demanding equality.
        if stated and not (alt.startswith(stated[:60]) or stated.startswith(alt[:60])):
            errors.append(
                f"Q{n}: alternative ({letter}) text does not match the gabarito's stated answer\n"
                f"        caderno : {q['alternatives'][LETTERS.index(letter)][:110]}\n"
                f"        gabarito: {g['correct_text'][:110]}"
            )


def validate_rows(rows, errors):
    if len(rows) != EXPECTED:
        errors.append(f"expected {EXPECTED} questions, got {len(rows)}")
    for r in rows:
        at = f"Q{r['number']}"
        if len(r["enunciado"]) < 50:
            errors.append(f"{at}: enunciado suspiciously short ({len(r['enunciado'])} chars)")
        if any(not a.strip() for a in r["alternatives"]):
            errors.append(f"{at}: empty alternative text")
        for f in ("comentario", "distratores", "conceito_chave"):
            if not r.get(f, "").strip():
                errors.append(f"{at}: empty {f}")
        if r["correct_index"] not in (0, 1, 2, 3):
            errors.append(f"{at}: correct_index out of range")


# ── diff against the set already on disk ──────────────────────────────────────

def report_diff(rows, out_dir):
    prev_path = os.path.join(out_dir, "merged.json")
    if not os.path.exists(prev_path):
        print("\nNo existing merged.json in --out; nothing to diff against.")
        return
    prev = {q["number"]: q for q in json.load(open(prev_path, encoding="utf-8"))}
    changed = {"enunciado": [], "alternatives": [], "correct_index": [],
               "comentario": [], "distratores": [], "conceito_chave": []}
    for r in rows:
        o = prev.get(r["number"])
        if not o:
            continue
        for f in changed:
            a, b = o.get(f), r.get(f)
            if isinstance(a, list) or isinstance(b, list):
                if [norm(x) for x in (a or [])] != [norm(x) for x in (b or [])]:
                    changed[f].append(r["number"])
            elif isinstance(a, int) or isinstance(b, int):
                if a != b:
                    changed[f].append(r["number"])
            elif norm(a) != norm(b):
                changed[f].append(r["number"])

    print("\nDIFF vs the merged.json already in --out")
    for f, nums in changed.items():
        line = f"  {f:<15} {len(nums):>3} changed"
        if nums and len(nums) <= 20:
            line += f"   {nums}"
        print(line)
    if changed["correct_index"]:
        print("\n  !! ANSWER KEY MOVED on " + ", ".join(f"Q{n}" for n in changed["correct_index"]))
        print("     Re-importing rewrites graded history's meaning — confirm with Karina first.")
    for n in changed["alternatives"][:8]:
        o, r = prev[n], next(x for x in rows if x["number"] == n)
        print(f"\n  --- Q{n} alternatives ---")
        for i, (a, b) in enumerate(zip(o["alternatives"], r["alternatives"])):
            if norm(a) != norm(b):
                print(f"    ({LETTERS[i]}) OLD: {a}")
                print(f"    ({LETTERS[i]}) NEW: {b}")
    for n in changed["enunciado"][:8]:
        o, r = prev[n], next(x for x in rows if x["number"] == n)
        diff = [l for l in difflib.unified_diff(o["enunciado"].split(), r["enunciado"].split(), lineterm="", n=0)
                if l[:1] in "+-" and not l.startswith(("+++", "---"))]
        if diff:
            print(f"\n  --- Q{n} enunciado ---")
            print("    " + " ".join(diff[:40]))


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="folder holding the two PDFs")
    ap.add_argument("--out", default=os.path.join("data", "simulado-100-v2"),
                    help="folder to diff against and (with --write) write merged.json into")
    ap.add_argument("--write", action="store_true", help="write merged.json (default: dry run)")
    args = ap.parse_args()

    qpath = os.path.join(args.src, QUESTIONS_PDF)
    gpath = os.path.join(args.src, GABARITO_PDF)
    for p in (qpath, gpath):
        if not os.path.exists(p):
            sys.exit(f"Missing PDF: {p}")

    errors = []
    questions, figures = parse_questions(qpath, errors)
    gabarito, grid = parse_gabarito(gpath, errors)

    print(f"parsed {len(questions)} questions, {len(gabarito)} gabarito entries, "
          f"{len(grid)} grid answers, {len(figures)} figures")

    cross_validate(questions, gabarito, grid, errors)

    rows = []
    for n in sorted(questions):
        q, g = questions[n], gabarito.get(n)
        if not g:
            continue
        rows.append({
            "number": n,
            "enunciado": q["enunciado"],
            "alternatives": q["alternatives"],
            "correct_index": LETTERS.index(g["correct_letter"]),
            "correct_letter": g["correct_letter"],
            "comentario": g["comentario"],
            "distratores": g["distratores"],
            "conceito_chave": g["conceito_chave"],
            "has_figure": q["has_figure"],
        })
    validate_rows(rows, errors)

    # figure-urls.json is written by the uploader, not here — but a figure that
    # moved to another question would silently show the wrong image.
    fig_path = os.path.join(args.out, "figure-urls.json")
    if os.path.exists(fig_path):
        known = {int(k) for k in json.load(open(fig_path, encoding="utf-8"))}
        if known != figures:
            errors.append(
                f"figure questions changed: PDF has {sorted(figures)}, "
                f"figure-urls.json has {sorted(known)} — re-run upload-simulado-figures.js"
            )

    spread = {l: sum(1 for r in rows if r["correct_letter"] == l) for l in LETTERS}
    print(f"answer spread  A={spread['A']} B={spread['B']} C={spread['C']} D={spread['D']}")
    print(f"figures on     {sorted(figures)}")

    if errors:
        print(f"\nVALIDATION FAILED — {len(errors)} problem(s):\n")
        for e in errors[:40]:
            print("  " + e)
        if len(errors) > 40:
            print(f"  ...and {len(errors) - 40} more")
        sys.exit(1)
    print("validation     PASS (answer key agrees across grid, gabarito text and caderno)")

    report_diff(rows, args.out)

    if not args.write:
        print("\nDry run — nothing written. Re-run with --write.")
        return
    os.makedirs(args.out, exist_ok=True)
    dest = os.path.join(args.out, "merged.json")
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(rows, fh, ensure_ascii=False, indent=1)
        fh.write("\n")
    print(f"\nWROTE {dest} ({len(rows)} questions)")


if __name__ == "__main__":
    main()
