#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * snapshot-resumos.js — READ-ONLY. Captures every Resumos page, its lessons and the
 * Resumos hubs' card lists, and writes a rollback file that restores them exactly:
 *
 *   node scripts/snapshot-resumos.js local   → parsed/resumos-rollback-2026-10-05-local.sql
 *   node scripts/snapshot-resumos.js prod    → parsed/resumos-rollback-2026-10-05-prod.sql
 *
 * Run it BEFORE parsed/resumos-v2-import.sql. Restore with run-sql.js against the
 * same database. The rollback deletes pages the import created (view='resumos',
 * id not in the snapshot — their lessons, cards and completions cascade), puts
 * slug/title/status/specialty/parent/notes and every lesson body back by id, and
 * rebuilds the hub cards with their original ids. Refuses to overwrite an existing
 * snapshot: a second run after the import would capture the NEW state.
 */
"use strict";

const fs = require("fs");
const path = require("path");
const postgres = require("postgres");

const target = process.argv[2];
if (!["local", "prod"].includes(target)) {
  console.error("usage: node scripts/snapshot-resumos.js <local|prod>");
  process.exit(1);
}
const OUT = path.join(__dirname, "..", "parsed", `resumos-rollback-2026-10-05-${target}.sql`);
if (fs.existsSync(OUT) && !process.argv.includes("--force")) {
  console.error(`${OUT} already exists — refusing to overwrite (it may hold the pre-import state). --force to replace.`);
  process.exit(1);
}

function prodUrl() {
  const env = fs.readFileSync(path.join(__dirname, "..", "app", ".env.local"), "utf8");
  const m = env.match(/^DATABASE_URL=(.+)$/m);
  if (!m) throw new Error("DATABASE_URL missing from app/.env.local");
  return m[1].trim().replace(/^["']|["']$/g, "");
}
const url = target === "local" ? "postgresql://postgres:postgres@127.0.0.1:55322/postgres" : prodUrl();

const q = (v) => (v == null ? "NULL" : typeof v === "number" ? String(v) : "'" + String(v).replace(/'/g, "''") + "'");

(async () => {
  const sql = postgres(url, { max: 1, prepare: false });
  try {
    const pages = await sql`
      SELECT id::int, slug, title, status, specialty_id, parent_id::int, notes
      FROM pages WHERE view = 'resumos' ORDER BY id`;
    const lessons = await sql`
      SELECT l.id::int, l.page_id::int, l.position, l.title, l.body_html
      FROM lessons l JOIN pages p ON p.id = l.page_id
      WHERE p.view = 'resumos' ORDER BY l.id`;
    const cards = await sql`
      SELECT n.id::int, n.source_page_id::int, n.target_page_id::int, n.position, n.label, n.icon, n.group_label, n.layout
      FROM nav_items n JOIN pages h ON h.id = n.source_page_id
      WHERE h.view = 'resumos' AND h.type = 'blurb-nav-hub' ORDER BY n.id`;

    const ids = pages.map((p) => p.id);
    const out = `-- resumos-rollback-2026-10-05-${target}.sql  (GENERATED by scripts/snapshot-resumos.js at ${new Date().toISOString()})
-- Restores the Resumos section to its state before parsed/resumos-v2-import.sql.
-- ${pages.length} pages, ${lessons.length} lessons, ${cards.length} hub cards. One transaction via run-sql.js.

-- 1. Hub cards out (rebuilt below with their original ids).
DELETE FROM nav_items WHERE source_page_id IN (
  SELECT id FROM pages WHERE view = 'resumos' AND type = 'blurb-nav-hub');

-- 2. Pages the import created (e.g. outros-resumos, new topics). Cascades their lessons,
--    cards and any completion recorded since.
DELETE FROM pages WHERE view = 'resumos' AND id NOT IN (${ids.join(", ")});

-- 3. Page fields back, by id.
UPDATE pages p SET slug = v.slug, title = v.title, status = v.status,
       specialty_id = v.specialty_id, parent_id = v.parent_id, notes = v.notes
FROM (VALUES
${pages.map((p) => `  (${p.id}, ${q(p.slug)}, ${q(p.title)}, ${q(p.status)}, ${p.specialty_id == null ? "NULL::int" : p.specialty_id}, ${p.parent_id == null ? "NULL::bigint" : p.parent_id}, ${q(p.notes)})`).join(",\n")}
) AS v(id, slug, title, status, specialty_id, parent_id, notes)
WHERE p.id = v.id;

-- 4. Lessons the import added to existing pages go; every original lesson body comes back.
DELETE FROM lessons WHERE page_id IN (${ids.join(", ")}) AND id NOT IN (${lessons.map((l) => l.id).join(", ")});
UPDATE lessons l SET title = v.title, body_html = v.body_html, position = v.position
FROM (VALUES
${lessons.map((l) => `  (${l.id}, ${l.position}, ${q(l.title)}, ${q(l.body_html)})`).join(",\n")}
) AS v(id, position, title, body_html)
WHERE l.id = v.id;

-- 5. Hub cards with their original ids.
INSERT INTO nav_items (id, source_page_id, target_page_id, position, label, icon, group_label, layout)
OVERRIDING SYSTEM VALUE VALUES
${cards.map((c) => `  (${c.id}, ${c.source_page_id}, ${c.target_page_id == null ? "NULL" : c.target_page_id}, ${c.position}, ${q(c.label)}, ${q(c.icon)}, ${q(c.group_label)}, ${q(c.layout)})`).join(",\n")};

SELECT status, count(*) AS resumos_pages FROM pages WHERE view = 'resumos' GROUP BY status ORDER BY status;
`;
    fs.writeFileSync(OUT, out, "utf8");
    console.log(`snapshot (${target}): ${pages.length} pages, ${lessons.length} lessons, ${cards.length} cards → ${OUT} (${(out.length / 1024 / 1024).toFixed(2)} MB)`);
  } finally {
    await sql.end();
  }
})().catch((e) => { console.error(e); process.exit(1); });
